### ISSUE TITLE
How does your repository work with Redis or any Queue Drivers?

### ISSUE THREAD

**Issue by sujit-baniya** [nztim/queue#2]
I cloned your repository and used `$queueManager->add(new Job)` and `qm:process` to execute the jobs... but nothing seems to be working... I don't see any jobs on Redis as I set `QUEUE_DRIVER=redis`

Please help on how the repository works and how I could make it work

**Comment by nztim** [comment]
This package has no Redis driver, it only works with a database queue and with a single worker process. It has different design aims than the built-in Laravel queue system which is more general purpose and scalable. 

I would be happy to help but recommend you use the Laravel queue system unless you have problems or a specific interest in using this one. I will be removing this from Packagist because I don't want to promote it for general use.
